---
title: "ggplot"
author: "Anandu R"
date: "6/15/2020"
output:
  html_document:
    df_print: paged
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Heirarchical Clustering 

Illustrating clusters 

```{r}
set.seed(96)
x = rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y = rnorm(12, mean = rep(c(1,2,1),each = 4), sd = 0.2)
plot(x, y, col = "orange", pch = 19,cex = 1.5)
text(x+0.05, y+0.05, labels = as.character(1:12))
```

### Step 1

Find the pairwise distance between each points using the dist() function

```{r}
data = data.frame(x,y)
distxy = dist(data)
distxy
```

### Step 2

Heirarchical Clustering using hclust()

```{r}
hClustering = hclust(distxy)
plot(hClustering)
```

```{r plclust}
myplclust <- function( hclust, lab=hclust$labels, lab.col=rep(1,length(hclust$labels)), hang=0.1,...){
  ## modifiction of plclust for plotting hclust objects *in colour*!
  ## Copyright Eva KF Chan 2009
  ## Arguments:
  ##    hclust:    hclust object
  ##    lab:        a character vector of labels of the leaves of the tree
  ##    lab.col:    colour for the labels; NA=default device foreground colour
  ##    hang:     as in hclust & plclust
  ## Side effect:
  ##    A display of hierarchical cluster with coloured leaf labels.
  y <- rep(hclust$height,2); x <- as.numeric(hclust$merge)
  y <- y[which(x<0)]; x <- x[which(x<0)]; x <- abs(x)
  y <- y[order(x)]; x <- x[order(x)]
  plot( hclust, labels=FALSE, hang=hang, ... )
  text( x=x, y=y[hclust$order]-(max(hclust$height)*hang),
        labels=lab[hclust$order], col=lab.col[hclust$order], 
        srt=90, adj=c(1,0.5), xpd=NA, ... )
}
```

Using a custom function to plot the clusters 

```{r}
myplclust(hClustering, lab = rep(1:3, each = 4), lab.col = rep(2:4, each = 4))
```

## Using the heatmap function to derive correlation between points in data 

Inorder to be able to organise the data with some logical way 
```{r}
dataAsMatrix = as.matrix(data)[sample(1:12),]
heatmap(dataAsMatrix)
```

