---
title: "Air Quality PM2.5 Case Study"
author: "Anandu R"
date: "7/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Air Quality PM2.5 Case Study

## Loading the data

```{r}
fileUrl2012 = "https://aqs.epa.gov/aqsweb/airdata/annual_conc_by_monitor_2012.zip"
fileUrl1999 = "https://aqs.epa.gov/aqsweb/airdata/annual_conc_by_monitor_1999.zip"
if(!file.exists('./data_1999.csv')&&!file.exists('./data_2012.csv')){
  download.file(fileUrl1999,"./data_1999.zip")
  download.file(fileUrl2012,"./data_2012.zip")
  unzip("data_2012.zip", exdir = getwd())
  unzip("data_1999.zip", exdir = getwd())
}
unlink('./data_1999.zip')
unlink('./data_2012.zip')
file.rename("annual_conc_by_monitor_1999.csv","data_1999.csv")
file.rename("annual_conc_by_monitor_2012.csv","data_2012.csv")
data_1999 = read.csv("data_1999.csv")
data_2012 = read.csv("data_2012.csv")
```

## Initial analysis on the data

Identifying the parameter code for PM2.5 data
```{r}
library(dplyr)
par_code = grep("PM2.5",data_1999$Parameter.Name)[1]
par_code = data_1999$Parameter.Code[par_code]
```

## Deleting files after completion
```{r}
unlink("data_1999.csv")
unlink("data_2012.csv")
```


